### ISSUE TITLE
[Q] Background rendering

### ISSUE THREAD

**Issue by emrsmsrli** [benkonz/gameboy_emulator#22]
Hi there @benkonz,

I'm developing a GBC emulator myself. In my implementation, all of the background render happens just before the h-blank period. Looking at your code, I wonder why you implemented background rendering like this. Is there a purpose of not rendering all background at once, but tile by tile every tick? 

Thanks.

**Comment by emrsmsrli** [comment]
May I add another question? 
Is there a purpose of maintaining a background buffer in the gpu? If I understood correctly, you're using it for obj priorities, right? Isn't maintaining only one line sufficient?

**Comment by benkonz** [comment]
> May I add another question?
> Is there a purpose of maintaining a background buffer in the gpu? If I understood correctly, you're using it for obj priorities, right? Isn't maintaining only one line sufficient?

You're right, the `background` variable in the `GPU` is used for sprite-background priority. [This](https://gbdev.gg8.se/wiki/articles/Video_Display#Sprite_Priorities_and_Conflicts) explains it, but basically if bit 7 in the obj properties byte is set, that sprite's pixel should be ignored if the background color is 1-3. Without that array, we wouldn't know what the BG color is. 

I think maintaining just the current line we are rendering would work, although I haven't tested it. My code is by no means perfect, and I think it fails [this](https://github.com/Gekkio/mooneye-gb/blob/master/tests/manual-only/sprite_priority.s) Mooneye GB test.

**Comment by benkonz** [comment]
> Hi there @benkonz,
> 
> I'm developing a GBC emulator myself. In my implementation, all of the background render happens just before the h-blank period. Looking at your code, I wonder why you implemented background rendering like this. Is there a purpose of not rendering all background at once, but tile by tile every tick?
> 
> Thanks.

I'm no means an expert on this, but, technically, the background rendering should happen during the LCD transfer, according to the table [here](https://gbdev.gg8.se/wiki/articles/Video_Display#FF41_-_STAT_-_LCDC_Status_.28R.2FW.29). For most games, I don't think it should make a difference.

I tried to emulate as close to a CRT as possible, so tile-by-tile for every scan line. You could probably get away with rendering the line-by-line, instead of tile-by-tile, which is what [this code does](http://imrannazar.com/GameBoy-Emulation-in-JavaScript:-GPU-Timings). I don't think rendering all of the background every H-Blank is correct.

**Comment by benkonz** [comment]
Hope that helps, happy to answer anymore questions you might have!

**Comment by emrsmsrli** [comment]
What I meant by 'all background' was all pixels in a single render line. Sorry about the confusion. And yes I agree that BG rendering should happen (and does in my impl too) in LCD Transfer. Thanks for the answers. Keep up the good work!
